# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
    - job: BuildJob
      pool: 
        vmImage: 'ubuntu-latest'
      steps:
        - script: dotnet build --configuration $(buildConfiguration)
          displayName: dotnet build $(buildConfiguration) 